language: objective-c
osx_image: xcode10.1
before_install:
    - brew tap vapor/homebrew-tap
    - brew upgrade
    - brew install vapor    
    - swift package resolve
    - gem install xcpretty
env:
    - JWT_TOKEN_SECRET="super-secret"
script:
    - swift package generate-xcodeproj
    - set -o pipefail && xcodebuild -scheme JWTTokenService-Package -enableCodeCoverage YES clean build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
